version: "3.8"

services:
  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge